server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=registration
    username: user
    password: user
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
        show_sql: true
        ddl-auto: create-drop
        generate-ddl: true
        hbm2ddl:
          auto: create

  # -> mail inbox address https://mailtrap.io
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 16a7cfaadc6e28
    password: 2a61f836e60d1c

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000