server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    #url: jdbc:sqlserver://EFG-ED0-V01-048;databaseName=registration
    url: jdbc:sqlserver://localhost;databaseName=registration
    #url: jdbc:sqlserver://Server=127.0.0.1;Database=registration;User Id=user;Password=user;
    #url: jdbc:sqlserver://127.0.0.1:1433/registration;instance=master;integratedSecurity=true
    username: user
    password: user
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
        show_sql: true
        ddl-auto: create-drop
        generate-ddl: true
        hbm2ddl:
          auto: create
  #mail:
    #host: localhost
    #port: 1025
    #username: hello
    #password: hello

    #properties:
      #mail:
        #smtp:
          #ssl:
            #trust: "*"
          #auth: true
          #starttls:
            #enable: true
          #connectiontimeout: 5000
          #timeout: 3000
          #writetimeout: 5000

